export const BOT = 'BOT';
export const GATEWAY = 'GATEWAY';
export const INVENTORY = 'INVENTORY';
export const SHOW_INVENTORY = 'SHOW_INVENTORY';
export const BUY_ITEM_FROM_USER = 'BUY_ITEM_FROM_USER';
export const TRADE_OFFER_CHANGED = 'TRADE_OFFER_CHANGED';
export const UPDATE_PENDING_TRADES = 'UPDATE_PENDING_TRADES';
