version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: ggcsgo
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - nginx_data:/etc/nginx/conf.d
    depends_on:
      - postgres
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "
        server {
          listen       80;
          listen  [::]:80;
          server_name  localhost;
          location /api/ {
            proxy_pass http://localhost:4000/;
          }
          location / {
            proxy_pass http://localhost:3000/;
          }
          error_page   500 502 503 504  /50x.html;
          location = /50x.html {
            root   /usr/share/nginx/html;
          }
        }" > /etc/nginx/conf.d/default.conf
        exec nginx -g 'daemon off;'

volumes:
  postgres_data:
  nginx_data:
